# .github/workflows/force-version.yml
name: Force NEW_VERSION for feature branch

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'Force NEW_VERSION to override bump (e.g. 0.11.31)'
        required: true

jobs:
  override-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Manually set NEW_VERSION and bump versions
        run: |
          NEW_VERSION=${{ github.event.inputs.new_version }}
          echo "Forcing NEW_VERSION=${NEW_VERSION}"

          # Manually override version in package.json

          cd typescript
          npm version --no-git-tag-version "${NEW_VERSION}"
          cd ../aws-lambda
          poetry version "${NEW_VERSION}"
          cd ../

          # Overwrite tag and commit
          git config --local user.email "Bumpversion"
          git config --local user.name "Bumpversion"
          git add package.json package-lock.json pyproject.toml poetry.lock
          git commit -m "Bump version to ${NEW_VERSION}"
          git tag -a -f -m "Bump version to ${NEW_VERSION}" "v${NEW_VERSION}"
          git push origin HEAD --follow-tags --force

          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV